workflows:
  android-build:
    name: Android Build
    instance_type: mac_mini_m1
    environment:
      groups:
        - gemini
    scripts:
      - name: Set up Android SDK and Node.js
        script: |
          echo "ANDROID_SDK_ROOT=$CM_ANDROID_SDK_ROOT" >> "$CM_ENV"
          echo "PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools" >> "$CM_ENV"
          echo "JAVA_HOME=$CM_JAVA_HOME" >> "$CM_ENV"
          brew install node
      - name: Install dependencies
        script: |
          npm install
      - name: Build web assets
        script: |
          npm run build
      - name: Add Android platform and Sync
        script: |
          # Agora ele vai ler o capacitor.config.ts do seu repo
          npx cap add android
          npx cap sync android
      - name: Build Android App
        script: |
          cd android
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/apk/debug/app-debug.apk
